### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ericbhanson**
Added code to set number of standard deviations and width of SMA window when creating Bollinger Bands.

### CODE REVIEW

**Comment by jealous** [comment]
Hi @ericbhanson ,  it looks like the diff has some problem.   I will merge the PR later manually.  Thanks for the contribution!

**Comment by ericbhanson** [comment]
Hi @jealous, you're welcome! I haven't had a chance to upload it yet to Git, but your code is a major part of some charting software I wrote for digital currencies. If you figure out what the source of the problem is, would you mind letting me know? I'm new to Git and would love to be able to learn from any mistakes.

**Comment by jealous** [comment]
Looks like we are using different line endings.  Never mind, I will close this PR and merge it into master directly.  Thanks for the contribution!

**Comment by jealous** [comment]
Hi @ericbhanson , I do have one question though.  I saw you add a function to parse the float number in the column name.  As far as I know, we could only use integer as window.  Do you have a special reason to add a float parsing function?

**Comment by ericbhanson** [comment]
Thanks for the heads up about line endings - I'll look for that in the future. 

Use case for the floats: when setting up the Bollinger Bands on my data, I noticed that the best fit was 2.5 standard deviations. To handle this, I added a float function.

**Comment by jealous** [comment]
Hi @ericbhanson ,

After some serious consideration, I decide not to merge this change.  Reasons are listed below:
* You could achieve your goal by doing following settings before getting any stats:
``` python
  StockDataFrame.BOLL_PERIOD = 10   # or other values you need
  StockDataFrame.BOLL_STD_TIMES = 2.5
```
  After you change them, the new values will be used for calculation.
* Your change requires to change the column name from `boll_ub` to `boll-ub`.  For backward compatibility reasons, I don't want to touch the name of the stats used very often.
* The new function which requires 2 more parameters actually cannot be used in the current column name parsing structure.  It only supports one window.  And add a window in the column name would require to change the name from `boll_ub` to `boll-ub`.  What's more, you will still get a attributes not found error because you actually initialize the `2.5_10_boll-ub` column but not the `boll-ub` column.  In order to initialize the column name specified by user, we need a way to pass the column name down to the calculation function, but it's not doable in current structure.

Anyway, thanks for the contribution and let me know if you have more requirements.  I will try to add them in the lib if I could 😄

**Comment by ericbhanson** [comment]
@jealous thanks for letting me know. So I understand: your main objection to the update is that it requires a change to column naming that would remove backwards compatibility, correct?

**Comment by jealous** [comment]
Yes.  Another consideration is that your requirement could be fulfilled by changing the class level configuration parameters.

**Comment by ericbhanson** [comment]
@jealous Got it. I would say that requiring the user to change settings on a file to support different use cases isn't a great long-term solution, but I understand your concern about backwards compatibility. Thanks for considering the addition!

**Comment by jealous** [comment]
No no no, not change settings on the source file.  Just change the setting in your code.  You code do that right after your `from stockstats import StockDataFrame`.

**Comment by ericbhanson** [comment]
Oh, I see - yes, that would definitely make things different!

**Comment by ericbhanson** [comment]
Can I suggest that you add that feature to the documentation instead? It would definitely be helpful for others to know too, I'm sure.

**Comment by jealous** [comment]
Good suggestion.  Will do that 😄

**Pull request closed without merging**
