### PR TITLE
Added vwap support

### PR DESCRIPTION
**Pull request by Arsh0023**
I have added Volume Weighted Average Price indicator support 

my knowledge of vwap is based on [](https://www.investopedia.com/terms/v/vwap.asp#:~:text=VWAP%20is%20calculated%20by%20adding,by%20the%20total%20shares%20traded.)

code sample:-
`stocks = StockDataFrame.retype(df)`
`print(stocks['vwap'].tail(10))`

gives output:- 
Datetime
2020-12-09 12:15:00+05:30    935.595807
2020-12-09 12:20:00+05:30    935.566596
2020-12-09 12:25:00+05:30    935.548274
2020-12-09 12:30:00+05:30    935.543816
2020-12-09 12:35:00+05:30    935.539725
2020-12-09 12:40:00+05:30    935.529548
2020-12-09 12:45:00+05:30    935.516953
2020-12-09 12:50:00+05:30    935.502845
2020-12-09 12:55:00+05:30    935.490450
2020-12-09 12:59:09+05:30    935.490450
Name: vwap, dtype: float64

### CODE REVIEW

**Comment by jealous** [comment]
Looks OK to me.  But the CI fails due to some formatting issue.  And we need a new test case to verify the output.  Please let me know if you can finish this.  Or I can start a new PR and you could review the change.

**Comment by jealous** [comment]
By the way, looks like `cumsum` accumulate all the previous value.  Usually, we specify a window for the data to accumulate.  Maybe we need to use a different method.

**Comment by Arsh0023** [comment]
> By the way, looks like `cumsum` accumulate all the previous value. Usually, we specify a window for the data to accumulate. Maybe we need to use a different method.

as vwap is calculated per day so it must start from the days start and end till current time, so maybe we can create a method whose default window maybe from the days start till current time

**Comment by jealous** [comment]
Looks like the build is still failing.

Actually, I think it's the user's responsibility to group the data.  Some of the users use this lib to process daily data.  We take no assumption on what the scale of the data is.  So I cannot properly add a function to group the data by days or by weeks, months

**Comment by Arsh0023** [comment]
> Looks like the build is still failing.
> 
> Actually, I think it's the user's responsibility to group the data. Some of the users use this lib to process daily data. We take no assumption on what the scale of the data is. So I cannot properly add a function to group the data by days or by weeks, months

yup the build is till failing i think you please open a new PR and I can review the change.

So we can add a vwap_window variable for user but what should be its default and all.

**Comment by jealous** [comment]
Close this PR.
This indicator is available in this commit now.
001331ac6d6f7ad4df00afc78f48eb61f53cf8d6

**Pull request closed without merging**
